# Generated by Django 3.2.3 on 2021-05-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shoes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='ФИО')),
                ('shoes_name', models.CharField(blank=True, max_length=500, verbose_name='Название обуви')),
                ('size', models.CharField(blank=True, max_length=500, verbose_name='Размер обуви')),
                ('pay_method', models.CharField(blank=True, max_length=500, verbose_name='Способ оплаты')),
                ('dostavka', models.CharField(blank=True, max_length=500, verbose_name='Способ доставки')),
                ('number', models.CharField(blank=True, max_length=500, verbose_name='Номер телефона')),
                ('adress', models.CharField(blank=True, max_length=500, verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
