# Generated by Django 3.2.3 on 2021-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_zayavka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='dostavka',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='pay_method',
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/photo', verbose_name='Image'),
        ),
    ]
